# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_ARCOS_timesTwo', PACKAGE = 'ARCOS', x)
}

rcpp_clip <- function(x, a, b) {
    .Call('_ARCOS_rcpp_clip', PACKAGE = 'ARCOS', x, a, b)
}

