# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clip a numeric vector
#' Clip a numeric vector between lower and upper bounds.
#'
#' @param x a numeric vector.
#' @param a lower bound (double).
#' @param b upper bound (double).
#'
#' @return a numeric vector.
#'
#' @examples
#' cat("no example")
rcpp_clip <- function(x, a, b) {
    .Call('_ARCOS_rcpp_clip', PACKAGE = 'ARCOS', x, a, b)
}

